name: Publish Docker image to Docker Hub and build CLI

on:
  push:
    branches:
      - main  # Or the branch name from which you want to trigger the action

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # or your required version

      - name: Install PyInstaller and Build Executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile numbCLI.py

      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: numbCLI-executable
          path: ./dist/numbCLI.exe

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push
        env:
          IMAGE_NAME: modelnumbersrv  # Name of your Docker image, replace it accordingly.
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
